[project]
name = "github-wikidata-bot"
version = "0.4.0"
requires-python = ">=3.8"

[tool.poetry]
name = "github-wikidata-bot"
version = "0.4.0"
description = "Updates Wikidata entries using metadata from github"
authors = ["konstin <konstin@mailbox.org>", "Michael Schönitzer <michael@schoenitzer.de>"]

[tool.poetry.dependencies]
python = "^3.8"
pywikibot = "^8.0.1"
mwparserfromhell = "^0.6.4"
CacheControl = { version = "^0.13.1", extras = ["filecache"] }
lockfile = "^0.12.2"
yarl = "^1.3"
msgpack = "^1.0.2"  # Required for cachecontrol

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
ruff = "0.0.287"

[tool.ruff]
extend-select = ["B", "PT", "PTH", "TRY", "UP"]
ignore = ["TRY400"]

[build-system]
requires = ["poetry~=1.0.0"]
build-backend = "poetry.masonry.api"
