name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # As of this writing, multidict isn't 3.13 compatible yet
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync
      - name: Check formatting
        run: uv run ruff format . --check
      - name: Run ruff
        run: uv run ruff check .
      - name: Run pytest
        run: uv run pytest
