name: Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # As of this writing, multidict isn't 3.13 compatible yet
        python-version: [ "3.10", "3.11", "3.12-dev" ]

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry==1.6.1
          poetry config virtualenvs.in-project true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Check formatting
        run: .venv/bin/ruff format . --check
      - name: Run pytest
        run: .venv/bin/pytest
      - name: Run ruff
        run: .venv/bin/ruff .
